channels:
  - anaconda
  - pytorch
dependencies:
  - python=3.9
  - numpy
  - matplotlib
  - scipy=1.9.1
  - pandas
  - seaborn
  - pip
  - scikit-learn
  - pip:
    - ruffus
    - tqdm
    - networkx
    - ipython
    - rdkit